---
- hosts: datacenter-west
  gather_facts: no
  tasks:
  # yum install epel-release
  - name: Add epel-release repo
  
  # yum install nginx
  - name: Install Nginx
    notify:
    - Start Nginx
  
  # copy files dir to /usr/share/nginx
  - name: copy files to /usr/share/nginx/html
    
  # sudo firewall-cmd --zone=public --permanent --add-service=http  
  - name: enable firewall

  # service nginx start
  handlers:
  - name: Start Nginx
  